FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy source files
COPY . ./

RUN apk add --no-cache \
    unzip \
    ca-certificates

RUN update-ca-certificates

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /picket ./internal/cmd/hub
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /picket-agent ./internal/cmd/agent
RUN mkdir -p /ssh-connectors && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w -s" -o /ssh-connectors/picket-connect_linux-amd64 ./internal/cmd/ssh-connect && \
    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-w -s" -o /ssh-connectors/picket-connect_linux-arm64 ./internal/cmd/ssh-connect && \
    CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-w -s" -o /ssh-connectors/picket-connect_darwin-amd64 ./internal/cmd/ssh-connect && \
    CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-w -s" -o /ssh-connectors/picket-connect_darwin-arm64 ./internal/cmd/ssh-connect

# ? -------------------------
FROM alpine:3.22

RUN apk add --no-cache ca-certificates

COPY --from=builder /picket /
COPY --from=builder /picket-agent /
COPY --from=builder /ssh-connectors /ssh-connectors

# Ensure data persistence across container recreations
VOLUME ["/picket_data"]

ENV PICKET_AGENT_BINARY=/picket-agent
ENV PICKET_SSH_CONNECTOR_DIR=/ssh-connectors

EXPOSE 8090

ENTRYPOINT [ "/picket" ]
CMD ["serve", "--http=0.0.0.0:8090"]
